name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#configuring-a-build-matrix
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: eval_test
      shell: bash
      working-directory: ${{runner.workspace}}
      run: ls -a

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}
      run: cmake .

    - name: Build
      working-directory: ${{runner.workspace}}
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: make BSP

#     - name: Test
#       working-directory: ${{runner.workspace}}/build
#       shell: bash
#       run: ctest -C $BUILD_TYPE
